#!/bin/bash
# Script to reorganize nrho-lagrangian-tori repository

set -e  # Exit on error

echo "========================================="
echo "Repository Reorganization Script"
echo "========================================="
echo ""

# Confirm with user
echo "This script will reorganize the repository structure."
echo "It will:"
echo "  - Create new directory structure"
echo "  - Move files to appropriate locations"
echo "  - Update Makefile and .gitignore"
echo ""
read -p "Continue? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    echo "Aborted."
    exit 1
fi

echo ""
echo "Creating directory structure..."

# Create main directories
mkdir -p src/cpp/headers
mkdir -p src/julia
mkdir -p data/initial_conditions
mkdir -p data/config
mkdir -p output
mkdir -p results
mkdir -p build
mkdir -p bin
mkdir -p docs/analysis
mkdir -p docs/paper
mkdir -p figures
mkdir -p scripts
mkdir -p tests

echo "✓ Directories created"
echo ""

echo "Moving C/C++ source files..."
# Move C/C++ source files
mv -v param.cc src/cpp/
mv -v seccp.c src/cpp/
mv -v fluxvp.c src/cpp/
mv -v rk78vp.c src/cpp/
mv -v rtbphp.c src/cpp/
mv -v campvp.c src/cpp/
mv -v scread.c src/cpp/
mv -v vbprintf.c src/cpp/

echo ""
echo "Moving C/C++ header files..."
# Move header files
mv -v complex.h src/cpp/headers/
mv -v grid.h src/cpp/headers/
mv -v matrix.h src/cpp/headers/
mv -v utils.h src/cpp/headers/
mv -v seccp.h src/cpp/headers/
mv -v fluxvp.h src/cpp/headers/
mv -v rk78vp.h src/cpp/headers/
mv -v rtbphp.h src/cpp/headers/
mv -v campvp.h src/cpp/headers/
mv -v scread.h src/cpp/headers/
mv -v vbprintf.h src/cpp/headers/

echo ""
echo "Moving Julia source files..."
# Move Julia files
mv -v main.jl src/julia/
mv -v dynamics.jl src/julia/
mv -v parameterization-method.jl src/julia/
mv -v util.jl src/julia/

echo ""
echo "Moving data files..."
# Move data files
mv -v approxQPO.csv data/initial_conditions/
mv -v approxQPO_p128.csv data/initial_conditions/
mv -v halo.csv data/initial_conditions/
mv -v NRHO_L1.csv data/initial_conditions/
mv -v NRHO_L2.csv data/initial_conditions/

mv -v curve_start_names.txt data/config/
mv -v nrho_start_names.txt data/config/
mv -v nrho_start.txt data/config/
mv -v torus_start_names.txt data/config/

echo ""
echo "Moving result/output files..."
# Move result files
mv -v param_single_kam_test.txt results/ 2>/dev/null || true
mv -v param_output.txt results/ 2>/dev/null || true
mv -v full_param_output.txt results/ 2>/dev/null || true
mv -v julia_output.txt results/ 2>/dev/null || true
mv -v julia_run2.txt results/ 2>/dev/null || true
mv -v julia_run3.txt results/ 2>/dev/null || true
mv -v mytraj.txt results/ 2>/dev/null || true

echo ""
echo "Moving documentation..."
# Move documentation files
mv -v KAM_TORUS_BUG_ANALYSIS.md docs/analysis/
mv -v TEST_RESULTS.md docs/analysis/
mv -v CONTINUATION_FIX.md docs/analysis/
mv -v SESSION_SUMMARY_2026-08-05.md docs/analysis/
mv -v PAPER_SUMMARY.md docs/analysis/
mv -v STATUS.md docs/

# Move paper directory
mv -v paper/* docs/paper/
rmdir paper

echo ""
echo "Moving figures..."
# Move figures
mv -v fig/2torusIC.svg figures/
rmdir fig

echo ""
echo "Moving test files..."
# Move test files
mv -v test.cpp tests/ 2>/dev/null || true

echo ""
echo "Moving build artifacts..."
# Move/clean build artifacts
mv -v *.o build/ 2>/dev/null || echo "No .o files to move"
mv -v param bin/ 2>/dev/null || echo "No param executable to move"

echo ""
echo "Cleaning up..."
# Clean up empty/temporary files
rm -f mypoint.txt 2>/dev/null || true

echo ""
echo "Creating .gitkeep files..."
# Add .gitkeep to empty directories that should be tracked
touch output/.gitkeep
touch build/.gitkeep
touch bin/.gitkeep

echo ""
echo "Creating README files for directories..."

# Output directory README
cat > output/README.md << 'EOF'
# Output Directory

This directory contains output files generated by the param executable.

## Output File Format

When param successfully computes a torus at a given epsilon value, it generates:

```
output_torus<epsilon>.txt
```

For example: `output_torus0.0001.txt`

## Contents

Each output file contains:
- Tolerance parameters (toltail, tolinva, tolinte)
- Rotation frequencies (omega)
- Epsilon value
- System parameters (lambda, mu)
- Grid dimensions (nn)
- Torus parameterization data (real-space coordinates for each grid point)

## Gitignore

This directory is gitignored to prevent large output files from being committed.
EOF

# Scripts directory README
cat > scripts/README.md << 'EOF'
# Scripts Directory

Utility scripts for building, testing, and running the code.

## Available Scripts

(To be added as needed)

## Future Ideas

- `run_tests.sh` - Run test suite
- `generate_figures.sh` - Generate all paper figures
- `benchmark.sh` - Performance benchmarking
- `setup.sh` - Initial environment setup
EOF

# Tests directory README
cat > tests/README.md << 'EOF'
# Tests Directory

Test files for verifying correctness of the implementation.

## Current Tests

- `test.cpp` - Basic C++ tests (if any)

## Future Test Suite

Consider adding:
- Unit tests for individual functions
- Integration tests for full pipeline
- Regression tests for known results
- Convergence tests for different parameters
EOF

echo "✓ README files created"
echo ""

echo "========================================="
echo "Reorganization Complete!"
echo "========================================="
echo ""
echo "Next steps:"
echo "  1. Update Makefile for new paths"
echo "  2. Update .gitignore"
echo "  3. Update Julia includes"
echo "  4. Test build: make clean && make"
echo "  5. Test Julia: julia --project=. src/julia/main.jl"
echo "  6. Review changes: git status"
echo ""
echo "Files are now organized in:"
echo "  src/       - Source code"
echo "  data/      - Input data"
echo "  output/    - Generated outputs"
echo "  results/   - Test results"
echo "  build/     - Build artifacts"
echo "  bin/       - Executables"
echo "  docs/      - Documentation"
echo "  figures/   - Generated figures"
echo ""
